Action cable
liman-rpg/forum_TN pull request #8
Opened 2017-11-09 21:20 UTC by liman-rpg

Action Cable
Comment

2017-11-16 09:49 UTC, vkurennov requested changes

2017-11-16 09:49 UTC, vkurennov commented on app/assets/javascripts/channels/answers.coffee
> +    # Called when the subscription has been terminated by the server
Если обработчик пустой, то зачем его писать?

2017-11-16 09:49 UTC, vkurennov commented on app/assets/javascripts/channels/questions.coffee
> +App.questions = App.cable.subscriptions.create "QuestionsChannel",
Зачем эта заглушка? У тебя же написано подключение в questions.coffee

2017-11-16 09:49 UTC, vkurennov commented on app/channels/answers_channel.rb
> +  def subscribed
Удали пустые методы

2017-11-16 09:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +          partial: 'answers/create.json.jbuilder',
Прощше было использовать `@answer.to_json`

2017-11-18 11:37 UTC, liman-rpg commented on app/controllers/answers_controller.rb
> +          partial: 'answers/create.json.jbuilder',
Если использовать  @answer.to_json , данные о attachments, votes, email и т.д. не передадутся.

2017-11-19 11:33 UTC, palkan-th requested changes

2017-11-19 11:33 UTC, palkan-th commented on app/assets/javascripts/channels/answers.coffee
> +    return if gon.current_user_id == answer.user_id
А что если у пользователя открыто несколько вкладок? Тогда в одной из них он ответа не увидит

2017-11-19 11:33 UTC, palkan-th commented on app/assets/javascripts/channels/comments.coffee
> +    return if gon.current_user_id == comment.user_id
Здесь тоже самое

2017-11-19 11:33 UTC, palkan-th commented on app/assets/javascripts/templates/answer.jst.skim
> +      -unless @answer.votes.exists?(user: gon.current_user_id)
А это будет работать?) Точно нет, в Skim у тебя просто JSON объект, этот код выполняется в браузере, а не на сервере

2017-11-20 07:56 UTC, liman-rpg commented on app/assets/javascripts/channels/answers.coffee
> +    return if gon.current_user_id == answer.user_id
Проверял, все работает . Не пойму что не так.

2017-11-21 08:00 UTC, vkurennov approved these changes

2017-11-21 09:10 UTC, merged